version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.production
    volumes:
      - ./src:/var/www/html/project
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/project
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge