services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.production
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    depends_on:
      - php