version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /root/project/docker/nginx/production.conf:/etc/nginx/conf.d/production.conf
      - /root/project:/var/www
    depends_on:
      - php

  php:
    image: php:7.4.9
    volumes:
      - ./src:/var/www/
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: always

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80
    restart: always