version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4.9-fpm
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd /path/to/project/src
            curl -sS https://getcomposer.org/installer | php
            php composer.phar install
      - run:
          name: Set up environment
          command: |
            cp .env.example .env.production
            php artisan key:generate
            php artisan migrate
      - run:
          name: Run PHPUnit tests
          command: |
            ./vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build