version: 2.1

jobs:
  build:
    docker:
      - image: php:7.4.9-fpm
        working_directory: /var/www
    steps:
      - checkout
      - run:
          name: Debug directory structure (Checking for composer.json)
          command: |
            echo "Current directory structure:"
            ls -al /var/www
      - run:
          name: Build Custom PHP Docker Image
          command: |
            docker build -t php:7.4.9-fpm ./docker/php
      - run:
          name: Install Composer (if not already installed in Dockerfile)
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
      - run:
          name: Install Laravel (if not already done in Dockerfile)
          command: |
            composer create-project --prefer-dist laravel/laravel src
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Run NPM build
          command: npm run prod
      - run:
          name: Copy .env.example to .env
          command: cp .env.example .env
      - run:
          name: Generate Laravel app key
          command: php artisan key:generate
      - run:
          name: Run migrations and tests
          command: |
            php artisan migrate --env=testing --force
            php artisan test

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate Docker to gcr.io
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker
      - run:
          name: Build Docker image for deployment
          command: |
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Google Container Registry
          command: docker push gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy coachtech --image gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 --region us-central1 --platform managed --quiet

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build