version: 2.1

jobs:
  build:
    docker:
      - image: php:7.4.9-fpm
        working_directory: /home/circleci/project/src
    steps:
      - checkout
      - run:
          name: Debug directory structure (Checking for composer.json)
          command: |
            echo "Current directory structure:"
            ls -al /home/circleci/project
            ls -al /home/circleci/project/src
      - run:
          name: Build Custom PHP Docker Image
          command: |
            docker build -t php:7.4.9-fpm ./docker/php
      - run:
          name: Debug composer.json existence
          command: |
            # コンテナ内で composer.json があるか確認
            echo "Checking if composer.json exists in /src"
            docker run --rm -v /home/circleci/project/src:/src php:7.4.9-fpm ls -al /src
      - run:
          name: Install dependencies
          command: |
            docker run --rm -v /home/circleci/project/src:/src php:7.4.9-fpm composer install --no-interaction --prefer-dist --optimize-autoloader
      - run:
          name: Install NPM dependencies
          command: npm install
      - run:
          name: Run NPM build
          command: npm run prod
      - run:
          name: Copy .env.example to .env
          command: cp .env.example .env
      - run:
          name: Generate Laravel app key
          command: php artisan key:generate
      - run:
          name: Run migrations and tests
          command: |
            php artisan migrate --env=testing --force
            php artisan test

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate Docker to gcr.io
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker
      - run:
          name: Build Docker image for deployment
          command: |
            # ビルドしたカスタムイメージを使用して、Cloud Run用のイメージをビルド
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Google Container Registry
          command: docker push gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy coachtech --image gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 --region us-central1 --platform managed --quiet

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build