version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/php:7.4.9-fpm
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Start Docker Compose
          command: docker-compose up -d
      - run:
          name: Install PHP dependencies
          command: docker-compose exec php composer install --no-interaction --prefer-dist --optimize-autoloader
      - run:
          name: Install NPM dependencies
          command: docker-compose exec php npm install
      - run:
          name: Run NPM build
          command: docker-compose exec php npm run prod
      - run:
          name: Copy .env.example to .env
          command: docker-compose exec php cp .env.example .env
      - run:
          name: Generate Laravel app key
          command: docker-compose exec php php artisan key:generate
      - run:
          name: Run migrations and tests
          command: |
            docker-compose exec php php artisan migrate --env=testing --force
            docker-compose exec php php artisan test

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate Docker to gcr.io
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker
      - run:
          name: Build Docker image for deployment
          command: docker build -t gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Google Container Registry
          command: docker push gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy coachtech --image gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 --region us-central1 --platform managed --quiet

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build