version: 2.1

jobs:
  build:
    docker:
      # カスタムイメージを使用するように変更
      - image: php:7.4.9-fpm
        working_directory: /home/circleci/project
    steps:
      - checkout
      - run: 
          name: Build Custom PHP Docker Image
          command: |
            # カスタムイメージをビルド（php:7.4.9-fpmを元にしたカスタムイメージをビルド）
            docker build -t my-custom-php-image:latest ./docker/php
      - run:
          name: Install dependencies
          command: |
            cd src
            # ビルドしたカスタムイメージを使用
            docker run --rm -v $(pwd):/app my-custom-php-image:latest composer install --no-interaction --prefer-dist --optimize-autoloader
      - run: npm install
      - run: npm run prod
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: php artisan migrate --env=testing --force
      - run: php artisan test

  deploy:
    docker:
      - image: google/cloud-sdk  # Cloud SDKのイメージを使用
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Authenticate Docker to gcr.io
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker
      - run:
          name: Build Docker image for deployment
          command: |
            # ビルドしたカスタムイメージを使用して、Cloud Run用のイメージをビルド
            docker build -t gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Google Container Registry
          command: docker push gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1
      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy coachtech --image gcr.io/$GOOGLE_PROJECT_ID/coachtech:$CIRCLE_SHA1 --region us-central1 --platform managed --quiet

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
