version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4.9-fpm
      environment:
          APP_ENV: local
          APP_KEY: base64:46ZVfBPWxoV2XZwwYgDZKW4k9GY2oCiIyban9QbV31g=
          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=laravel_db
          DB_USERNAME=laravel_user
          DB_PASSWORD=laravel_pass
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: circleci
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
              libpng-dev \
              libjpeg62-turbo-dev \
              libfreetype6-dev \
              zip \
              libzip-dev \
              git \
              unzip \
              curl \
              && docker-php-ext-configure zip \
              && docker-php-ext-install gd zip pdo pdo_mysql bcmath

      # Composerのインストール
      - run:
          name: Install Composer
          command: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=compose
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit -d memory_limit=2048M --debug

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build